id: I00A00492
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T07:24:38+00:00'
last_modified: '2022-06-07T13:35:49.653604+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6329
  title: ས་སྐྱའི་གནས་བཤད་སྙན་བརྒྱུད་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4C24:
      image_group_id: I3CN6331
      title: ''
      total_pages: 268
      order: 1
      base_file: 4C24.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
